controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.224
    wheel_radius: 0.0325
    use_stamped_vel: true

    # Velocity limits
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.26
    linear.x.min_velocity: -0.26
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 1.0
    linear.x.min_acceleration: -1.0

    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 2.0
    angular.z.min_acceleration: -2.0

    cmd_vel_timeout: 0.5